In [1]:
import numpy as np
my_list=[1,2,3]


In [2]:
mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(1)

array([1.])

In [14]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,3,50)

array([0.        , 0.06122449, 0.12244898, 0.18367347, 0.24489796,
       0.30612245, 0.36734694, 0.42857143, 0.48979592, 0.55102041,
       0.6122449 , 0.67346939, 0.73469388, 0.79591837, 0.85714286,
       0.91836735, 0.97959184, 1.04081633, 1.10204082, 1.16326531,
       1.2244898 , 1.28571429, 1.34693878, 1.40816327, 1.46938776,
       1.53061224, 1.59183673, 1.65306122, 1.71428571, 1.7755102 ,
       1.83673469, 1.89795918, 1.95918367, 2.02040816, 2.08163265,
       2.14285714, 2.20408163, 2.26530612, 2.32653061, 2.3877551 ,
       2.44897959, 2.51020408, 2.57142857, 2.63265306, 2.69387755,
       2.75510204, 2.81632653, 2.87755102, 2.93877551, 3.        ])

In [28]:
arr = np.random.rand(5)
arr

array([0.80342438, 0.19240755, 0.93820323, 0.37356915, 0.25750797])

In [36]:
arr=arr.reshape(5)
print(arr)
arr.shape

[0.80342438 0.19240755 0.93820323 0.37356915 0.25750797]


(5,)

In [42]:
ar=np.arange(25)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
ar1=np.random.rand(13)
ar1

array([0.27455383, 0.55407436, 0.37494763, 0.93417392, 0.35607128,
       0.88876483, 0.43874876, 0.32132972, 0.00565282, 0.18426982,
       0.85982388, 0.91063459, 0.32772825])

In [47]:
ar1=np.random.randn(5) 
ar1

array([ 1.02617872, -1.07852287,  0.61744057,  1.04252194, -0.83355426])

## Numpy operations

In [48]:
from numpy import *
arr=arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [52]:
arr/arr

C:\Users\admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [53]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [54]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [55]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [56]:
arr/100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [58]:
arr1=arange(0,5)
arr1

array([0, 1, 2, 3, 4])

In [59]:
arr+arr1

ValueError: operands could not be broadcast together with shapes (11,) (5,) 